# Generated by Django 4.0.5 on 2022-06-06 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.IntegerField()),
                ('date', models.DateField()),
                ('paymeth', models.CharField(max_length=16, verbose_name='payment method')),
                ('orderer', models.CharField(max_length=32)),
                ('receiver', models.CharField(max_length=32, verbose_name='recipient information')),
                ('delivery', models.CharField(max_length=32, verbose_name='Shipping method')),
                ('freight', models.CharField(max_length=16, verbose_name='Shipping fee payment method')),
                ('address', models.CharField(max_length=128, verbose_name='shipping receiver address')),
                ('obj1_name', models.CharField(max_length=32)),
                ('obj1_model', models.CharField(max_length=32)),
                ('obj1_unit', models.CharField(max_length=8)),
                ('obj1_amount', models.IntegerField()),
                ('obj1_uprice', models.IntegerField()),
                ('obj1_tprice', models.IntegerField()),
                ('obj2_name', models.CharField(max_length=32)),
                ('obj2_model', models.CharField(max_length=32)),
                ('obj2_unit', models.CharField(max_length=8)),
                ('obj2_amount', models.IntegerField()),
                ('obj2_uprice', models.IntegerField()),
                ('obj2_tprice', models.IntegerField()),
                ('obj3_name', models.CharField(max_length=32)),
                ('obj3_model', models.CharField(max_length=32)),
                ('obj3_unit', models.CharField(max_length=8)),
                ('obj3_amount', models.IntegerField()),
                ('obj3_uprice', models.IntegerField()),
                ('obj3_tprice', models.IntegerField()),
                ('obj4_name', models.CharField(max_length=32)),
                ('obj4_model', models.CharField(max_length=32)),
                ('obj4_unit', models.CharField(max_length=8)),
                ('obj4_amount', models.IntegerField()),
                ('obj4_uprice', models.IntegerField()),
                ('obj4_tprice', models.IntegerField()),
                ('obj5_name', models.CharField(max_length=32)),
                ('obj5_model', models.CharField(max_length=32)),
                ('obj5_unit', models.CharField(max_length=8)),
                ('obj5_amount', models.IntegerField()),
                ('obj5_uprice', models.IntegerField()),
                ('obj5_tprice', models.IntegerField()),
                ('obj6_name', models.CharField(max_length=32)),
                ('obj6_model', models.CharField(max_length=32)),
                ('obj6_unit', models.CharField(max_length=8)),
                ('obj6_amount', models.IntegerField()),
                ('obj6_uprice', models.IntegerField()),
                ('obj6_tprice', models.IntegerField()),
                ('total_up', models.CharField(max_length=64, verbose_name='total amount in upper case')),
                ('total_num', models.IntegerField()),
                ('remark', models.CharField(max_length=256)),
                ('manager', models.CharField(max_length=16)),
                ('phone', models.BigIntegerField()),
                ('form_maker', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=16, verbose_name='The position of the employee, tables connected by id')),
            ],
        ),
        migrations.CreateModel(
            name='PersonnelInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=16)),
                ('pwd', models.CharField(max_length=16)),
                ('pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrderManagement.position', verbose_name='The position of the employee, tables connected by id')),
            ],
        ),
    ]
