# Generated by Django 4.0.5 on 2022-06-14 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OrderManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertable',
            name='address',
            field=models.CharField(max_length=128, verbose_name='到货地址'),
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='date',
            field=models.DateField(verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='delivery',
            field=models.CharField(max_length=32, verbose_name='运输方式'),
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='form_maker',
            field=models.CharField(max_length=16, verbose_name='制单人'),
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='freight',
            field=models.CharField(max_length=16, verbose_name='运费支付'),
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='manager',
            field=models.CharField(max_length=16, verbose_name='业务经理'),
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='oid',
            field=models.IntegerField(verbose_name='订单编号'),
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='orderer',
            field=models.CharField(max_length=32, verbose_name='订货单位'),
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='paymeth',
            field=models.CharField(max_length=16, verbose_name='结算方式'),
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='phone',
            field=models.BigIntegerField(verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='receiver',
            field=models.CharField(max_length=32, verbose_name='收货人'),
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='remark',
            field=models.CharField(max_length=256, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='total_num',
            field=models.IntegerField(verbose_name='合计'),
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='total_up',
            field=models.CharField(max_length=64, verbose_name='大写'),
        ),
        migrations.AlterField(
            model_name='personnelinfo',
            name='pos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrderManagement.position', verbose_name='职位'),
        ),
        migrations.AlterField(
            model_name='position',
            name='position',
            field=models.CharField(max_length=16, verbose_name='部门'),
        ),
    ]
