# Generated by Django 4.0.5 on 2022-06-15 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OrderManagement', '0002_alter_ordertable_address_alter_ordertable_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField(unique=True, verbose_name='用户编号')),
                ('name', models.CharField(max_length=16, verbose_name='客户姓名')),
                ('phone', models.BigIntegerField(verbose_name='客户电话')),
                ('organization', models.CharField(max_length=32, verbose_name='客户单位')),
                ('address', models.CharField(max_length=64, verbose_name='客户地址')),
                ('job_title', models.CharField(max_length=16, verbose_name='客户职务')),
                ('remark', models.CharField(max_length=64, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=16)),
                ('pwd', models.CharField(max_length=16)),
                ('pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrderManagement.position', verbose_name='职位')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.IntegerField(unique=True, verbose_name='产品编号')),
                ('name', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=32)),
                ('unit', models.CharField(max_length=8)),
                ('amount', models.IntegerField()),
                ('unit_price', models.IntegerField()),
                ('total_price', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='ordertable',
            name='obj2_amount',
        ),
        migrations.RemoveField(
            model_name='ordertable',
            name='obj2_model',
        ),
        migrations.RemoveField(
            model_name='ordertable',
            name='obj2_name',
        ),
        migrations.RemoveField(
            model_name='ordertable',
            name='obj2_tprice',
        ),
        migrations.RemoveField(
            model_name='ordertable',
            name='obj2_unit',
        ),
        migrations.RemoveField(
            model_name='ordertable',
            name='obj2_uprice',
        ),
        migrations.RemoveField(
            model_name='ordertable',
            name='obj3_amount',
        ),
        migrations.RemoveField(
            model_name='ordertable',
            name='obj3_model',
        ),
        migrations.RemoveField(
            model_name='ordertable',
            name='obj3_name',
        ),
        migrations.RemoveField(
            model_name='ordertable',
            name='obj3_tprice',
        ),
        migrations.RemoveField(
            model_name='ordertable',
            name='obj3_unit',
        ),
        migrations.RemoveField(
            model_name='ordertable',
            name='obj3_uprice',
        ),
        migrations.RemoveField(
            model_name='ordertable',
            name='obj4_amount',
        ),
        migrations.RemoveField(
            model_name='ordertable',
            name='obj4_model',
        ),
        migrations.RemoveField(
            model_name='ordertable',
            name='obj4_name',
        ),
        migrations.RemoveField(
            model_name='ordertable',
            name='obj4_tprice',
        ),
        migrations.RemoveField(
            model_name='ordertable',
            name='obj4_unit',
        ),
        migrations.RemoveField(
            model_name='ordertable',
            name='obj4_uprice',
        ),
        migrations.RemoveField(
            model_name='ordertable',
            name='obj5_amount',
        ),
        migrations.RemoveField(
            model_name='ordertable',
            name='obj5_model',
        ),
        migrations.RemoveField(
            model_name='ordertable',
            name='obj5_name',
        ),
        migrations.RemoveField(
            model_name='ordertable',
            name='obj5_tprice',
        ),
        migrations.RemoveField(
            model_name='ordertable',
            name='obj5_unit',
        ),
        migrations.RemoveField(
            model_name='ordertable',
            name='obj5_uprice',
        ),
        migrations.RemoveField(
            model_name='ordertable',
            name='obj6_amount',
        ),
        migrations.RemoveField(
            model_name='ordertable',
            name='obj6_model',
        ),
        migrations.RemoveField(
            model_name='ordertable',
            name='obj6_name',
        ),
        migrations.RemoveField(
            model_name='ordertable',
            name='obj6_tprice',
        ),
        migrations.RemoveField(
            model_name='ordertable',
            name='obj6_unit',
        ),
        migrations.RemoveField(
            model_name='ordertable',
            name='obj6_uprice',
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='oid',
            field=models.IntegerField(unique=True, verbose_name='订单编号'),
        ),
        migrations.DeleteModel(
            name='PersonnelInfo',
        ),
        migrations.AddField(
            model_name='customer',
            name='correspond',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrderManagement.personnel', to_field='pid', verbose_name='负责经理'),
        ),
    ]
