# Generated by Django 4.0.5 on 2022-06-15 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OrderManagement', '0003_customer_personnel_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertable',
            name='obj1_amount',
        ),
        migrations.RemoveField(
            model_name='ordertable',
            name='obj1_model',
        ),
        migrations.RemoveField(
            model_name='ordertable',
            name='obj1_name',
        ),
        migrations.RemoveField(
            model_name='ordertable',
            name='obj1_tprice',
        ),
        migrations.RemoveField(
            model_name='ordertable',
            name='obj1_unit',
        ),
        migrations.RemoveField(
            model_name='ordertable',
            name='obj1_uprice',
        ),
        migrations.RemoveField(
            model_name='ordertable',
            name='total_num',
        ),
        migrations.RemoveField(
            model_name='ordertable',
            name='total_up',
        ),
        migrations.RemoveField(
            model_name='product',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='product',
            name='univalent',
            field=models.IntegerField(default=1, verbose_name='单价'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(max_length=32, verbose_name='规格型号'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=32, verbose_name='产品名称'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(max_length=8, verbose_name='单位'),
        ),
        migrations.CreateModel(
            name='Include',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='数量')),
                ('oid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrderManagement.ordertable', to_field='oid', verbose_name='订单')),
                ('rid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrderManagement.product', to_field='rid', verbose_name='产品')),
            ],
        ),
    ]
