# Generated by Django 4.0.5 on 2022-06-15 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OrderManagement', '0004_remove_ordertable_obj1_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertable',
            name='address',
        ),
        migrations.RemoveField(
            model_name='ordertable',
            name='orderer',
        ),
        migrations.AddField(
            model_name='ordertable',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='OrderManagement.customer', to_field='cid', verbose_name='订货人'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrderManagement.personnel', to_field='pid', verbose_name='业务经理'),
        ),
    ]
