# Generated by Django 4.0.5 on 2022-06-15 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OrderManagement', '0010_alter_ordertable_form_maker_alter_ordertable_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertable',
            name='manager',
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='form_maker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrderManagement.personnel', to_field='pid', verbose_name='制表人'),
        ),
    ]
