# Generated by Django 4.0.5 on 2022-06-15 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrderManagement', '0011_remove_ordertable_manager_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertable',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='ordertable',
            name='form_maker',
        ),
        migrations.DeleteModel(
            name='Include',
        ),
        migrations.DeleteModel(
            name='OrderTable',
        ),
    ]
