# Generated by Django 4.0.5 on 2022-06-15 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OrderManagement', '0012_remove_ordertable_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.IntegerField(unique=True, verbose_name='订单编号')),
                ('date', models.DateField(verbose_name='日期')),
                ('receiver', models.CharField(max_length=32, verbose_name='收货人')),
                ('paymeth', models.CharField(max_length=16, verbose_name='结算方式')),
                ('delivery', models.CharField(max_length=32, verbose_name='运输方式')),
                ('freight', models.CharField(max_length=16, verbose_name='运费支付')),
                ('remark', models.CharField(max_length=256, verbose_name='备注')),
                ('phone', models.BigIntegerField(verbose_name='电话')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrderManagement.customer', to_field='cid', verbose_name='订货人')),
                ('form_maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrderManagement.personnel', to_field='pid', verbose_name='制表人')),
            ],
        ),
        migrations.CreateModel(
            name='Include',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='数量')),
                ('oid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrderManagement.ordertable', to_field='oid', verbose_name='订单')),
                ('rid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrderManagement.product', to_field='rid', verbose_name='产品')),
            ],
        ),
    ]
