# Generated by Django 4.0.5 on 2022-06-17 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderManagement', '0013_ordertable_include'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertable',
            name='paymeth',
        ),
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.SmallIntegerField(choices=[(2, '女'), (1, '男')], default=1, verbose_name='性别'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordertable',
            name='pay_method',
            field=models.SmallIntegerField(choices=[(1, '现金'), (2, '转账')], default=1, verbose_name='结算方式'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='cid',
            field=models.IntegerField(unique=True, verbose_name='客户编号'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='job_title',
            field=models.CharField(blank=True, max_length=16, verbose_name='客户职务'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='organization',
            field=models.CharField(blank=True, max_length=32, verbose_name='客户单位'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='remark',
            field=models.CharField(blank=True, max_length=64, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='delivery',
            field=models.SmallIntegerField(choices=[(1, '送货上门'), (2, '物流点自取'), (3, '仓库自提')], verbose_name='运输方式'),
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='receiver',
            field=models.CharField(blank=True, max_length=32, verbose_name='收货人'),
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='remark',
            field=models.CharField(blank=True, max_length=256, verbose_name='备注'),
        ),
    ]
