# Generated by Django 4.0.5 on 2022-06-18 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OrderManagement', '0014_remove_ordertable_paymeth_customer_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='correspond',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='OrderManagement.personnel', to_field='pid', verbose_name='负责经理'),
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OrderManagement.customer', to_field='cid', verbose_name='订货人'),
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='form_maker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='OrderManagement.personnel', to_field='pid', verbose_name='制表人'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='pos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='OrderManagement.position', verbose_name='职位'),
        ),
    ]
