# Generated by Django 4.0.5 on 2022-06-18 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OrderManagement', '0015_alter_customer_correspond_alter_ordertable_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='OrderManagement.customer', to_field='cid', verbose_name='订货人'),
        ),
    ]
