# Generated by Django 4.0.5 on 2022-06-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderManagement', '0016_alter_customer_gender_alter_ordertable_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='job_title',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='客户职务'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='organization',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='客户单位'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='remark',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='receiver',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='收货人'),
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='remark',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='备注'),
        ),
    ]
