# Generated by Django 4.0.5 on 2022-07-16 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderManagement', '0020_remove_product_univalent_include_univalent'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertable',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '未审核'), (2, '审核通过'), (3, '待付款'), (4, '待发货'), (5, '待收货'), (6, '待付尾款'), (7, '完成')], default=1, verbose_name='订单状态'),
            preserve_default=False,
        ),
    ]
